### ISSUE TITLE
SSL Share URL configurations behind Nginx

### ISSUE THREAD

**Issue by howkymike** [Acosix/alfresco-keycloak#12]
Hello @AFaust 
Your addon looks really awesome, I successfully set up the Repository part (I can create a user in Keycloak and then sign in to Alfresco).
Unfortunately, **I have a problem with the Share configuration**. After clicking _**Login with SSO**_, I'm getting a "Something wrong with this page..." error. In the logs I can see:
```
SEVERE: Servlet.service() for servlet [Spring Surf Dispatcher Servlet] in context with path [/share] threw exception
org.alfresco.error.AlfrescoRuntimeException: 04180000 Failed to retrieve access token due to HTTP error 400: Bad Request
        at de.acosix.alfresco.keycloak.share.web.KeycloakAuthenticationFilter.getAccessToken(KeycloakAuthenticationFilter.java:1738)
        at de.acosix.alfresco.keycloak.share.web.KeycloakAuthenticationFilter.handleAlfrescoResourceAccessToken(KeycloakAuthenticationFilter.java:1628)
        at de.acosix.alfresco.keycloak.share.web.KeycloakAuthenticationFilter.onKeycloakAuthenticationSuccess(KeycloakAuthenticationFilter.java:912)
        at de.acosix.alfresco.keycloak.share.web.KeycloakAuthenticationFilter.processFilterAuthentication(KeycloakAuthenticationFilter.java:721)
        at de.acosix.alfresco.keycloak.share.web.KeycloakAuthenticationFilter.processKeycloakAuthenticationAndActions(KeycloakAuthenticationFilter.java:615)
        at de.acosix.alfresco.keycloak.share.web.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:488)
        at org.springframework.extensions.webscripts.servlet.BeanProxyFilter.doFilter(BeanProxyFilter.java:80)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.alfresco.web.site.servlet.MTAuthenticationFilter.doFilter(MTAuthenticationFilter.java:81)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

2021-05-18 14:16:12,425  ERROR [alfresco.web.site] [http-nio-8080-exec-9] org.alfresco.error.AlfrescoRuntimeException: 04180000 Failed to retrieve access token due to HTTP error 400: Bad Request
```
My share configuration:
- **auth-server-url** -> `https://my.domain.com/auth` (when I change it to http://localhost:8085, the form action URL i in the login page is also localhost, so it is unavailable)
-  prefix of every **endpoint-url** is `http://localhost:8080`
I attached full share-config-custom.xml and nginx.conf.
[configFiles.zip](https://github.com/Acosix/alfresco-keycloak/files/6501226/configFiles.zip)

Alfresco Repository, Share, Keyclock are running on a single machine (standalone/zip installation) on localhost/0.0.0.0. They are behind Nginx with Let's encrypt.

I also tried to following setup:
-  **directAuthHost** to `localhost:8085` (keycloak is running on 8085, becasue Alfresco Repo is on 8080),
-  **auth-server-url** to `https://my.domain.com/auth`
-  **ssl-required** to `external`

But then, when I click "Sign with SSO", accept the "Form is not secure" message (Chrome browser), provide credentials in Keyclock and click "Log in", it redirects be again to Alfresco login page and in the logs I can see the following error:

`2021-05-18 14:04:59,104 ERROR [de.acosix.alfresco.keycloak.deps.keycloak.adapters.OAuthRequestAuthenticator] [http-nio-8080-exec-42] failed verification of token: Invalid token issuer. Expected 'http://my.domain.com/auth/realms/alfresco', but was 'https://my.domain.com/auth/realms/alfresco'
2021-05-18 14:04:59,106 WARN  [de.acosix.alfresco.keycloak.share.web.KeycloakAuthenticationFilter] [http-nio-8080-exec-42] Keycloak authentication failed due to <missing AuthenticationError details in request context>`

**Comment by AFaust** [comment]
Hi Michal,

just to make sure: Did you work out the configuration on your own or did you notice/find the [work-in-progress documentation](https://github.com/Acosix/alfresco-keycloak/blob/docs-wip/docs/Simple-Configuration.md)? Unfortunately regular work is keeping me busy, so I have not had a chance to continue work on that documentation for a while now.

For the initial HTTP 400 error, I would ask that you check in Keycloak with enabled event logging for the CODE_TO_TOKEN / CODE_TO_TOKEN_ERROR, as well as with enabled debug in the Keycloak logs, what specifically Keycloak complains about. My initial guess would be that you have not (yet) set up your Keycloak instance to support token exchange between Share and Repository for the 100% "proper" authentication delegation between the two applications.
The `directAuthHost` is not required when the auth-server-url can be properly resolved from the Repository / Share host itself. It only exists for those rare cases, where you might configure a URL with a host name that is externally resolveable, but not internally (e.g. different domain names for access from outside the network / DMZ than within), or you want to avoid the extra roundtrip via the (public) proxy and go straight to Keycloak (or use a different, internal proxy on a different host).
Your second / additional attempts with the configuration changes actually failed way before the point where the initial one failed, so they are definitely not the way to go. With the configuration for the first attempt, you have two ways to move forward:

1. enable / set up token exchange in Keycloak
2. set `<perform-token-exchange>false</perform-token-exchange>` in the `<keycloak-auth-config>` section in share-config-custom.xml to disable its use for delegation between Share and Repository. You likely also will have to disable `keycloak.adapter.verify-token-audience` in the Repository, but to be honest, since adding token exchange as the default (proper) method of delegation, I have not tested the simple "token passthru" all that much.

**Comment by howkymike** [comment]
Thank you for the immediate response and the right directions. I had followed your documentation (or at least tried to) and configured token-exchange.
After setting ***verify-token-audience*** and  ***perform-token-exchange*** to `false` **it is finally working**.

But why the token exchange does not work?
I enabled token_exachnage feature, and in the `realm-management` client configured Authorization.
In the Keycloak I can see following error:
`20:38:50,570 WARN  [org.keycloak.events] (default task-9) type=TOKEN_EXCHANGE_ERROR, realmId=alfresco, clientId=alfresco-share, userId=null, ipAddress=my.domain.com/auth, error=invalid_token, reason='subject_token validation failure', auth_method=token_exchange, grant_type=urn:ietf:params:oauth:grant-type:token-exchange, client_auth_method=client-secret`
(the ipAddres is my.domain.com/auth but keycloak is running on 0.0.0.0, could that be an issue?)

**Comment by AFaust** [comment]
The IP does not really matter. The message clearly states an issue with the validation of the subject token, meaning the token Share received for the authenticated user and is now trying to exchange for a token for the same user towards the backend. I must admit I can't remember encountering this error in my own use / tests so far, so don't have an immediate idea as to the cause. I'll have a think about it and re-check the config files ZIP when I have some more time...

**Comment by howkymike** [comment]
Well.. I played with Keyclock and now I have another errror:
`20:59:10,546 WARN  [org.keycloak.events] (default task-91) type=TOKEN_EXCHANGE_ERROR, realmId=alfresco, clientId=alfresco-share, userId=null, ipAddress=my.domain.com/auth, error=not_allowed, reason='client not allowed to exchange to audience', auth_method=token_exchange, grant_type=urn:ietf:params:oauth:grant-type:token-exchange, client_auth_method=client-secret`

But then I also imported your `test` realm and it works, so it must be a problem with my realm's config.

**Comment by ayian2004** [comment]
Dear @howkymike 
Because I am facing similar issues, when you say that you have used @AFaust test realm, do you mean this one: https://github.com/Acosix/alfresco-keycloak/blob/master/share/src/test/docker/test-realm.json?
Did you changed it to match your instance?

**Comment by howkymike** [comment]
Hi @ayian2004,
yes indeed, I only changed the URLs. 
I guess you can't import because you did not change the variables to valid values (i.e. ${docker.tests.repositoryPort}  -> 8080).

**Comment by AFaust** [comment]
@howkymike The `client not allowed to exchange to audience` error in your own setup (before importing my test realm) has to do with the "Authorization" configuration in the `realm-management' application. In my WIP docs I wrote that various names include a `<idOfRepositoryClient>` fragment - this is meant as a placeholder for the client ID. Now, there can be some confusion, which I should probably make an effort to clear up in the docs, that this "client ID" does not mean the "Client ID" as displayed in the Keycloak UI, but the actual, technical DB ID of the client in the Keycloak database. This is one aspect where I think Keycloak UI really sucks - in order to get to that ID, I have not found any other way than to inspect the JSON response from Keycloak when loading the list of clients, and extract the ID from there.

**Comment by howkymike** [comment]
@AFaust wow... so many hours wasted, why would anyone program it to use an internal DB ID? Thank you very much - it worked on the first attempt.
For future readers, you can easily obtain client's ID using:
1. REST API
`curl -H 'Accept: application/json' -H "Authorization: Bearer ${TOKEN}" --location --request GET 'https://epm.epmflow.com/auth/admin/realms/alfresco/clients'`
2. By clicking _Export_ action in the _Clients_ tab

**Comment by AFaust** [comment]
No, I did not try import existing Alfresco users into Keycloak. The use cases I had so far either dealt with adding Keycloak quite early, when only a few users existed and could easily be recreated manually in Keycloak, or an external sources (AD-like) was used, so importing via LDAP or simply "as-people-log-in" was sufficient.

**Comment by ayian2004** [comment]
So I did manage to load the test-realm.json and also updated the <idOfRepositoryClient> fragment using the actual id as stored in the keycloak internal db, but when I click the "Login via SSO button"
![image](https://user-images.githubusercontent.com/1390684/121201345-20b2fb80-c87d-11eb-9e4c-47e7dd4c57ac.png)
I am getting a wrong redirect_uri.
this is the address populated: 
https://foresight.eurodyn.com/auth/realms/FORESIGHT/protocol/openid-connect/auth?response_type=code&client_id=alfresco-share&redirect_uri=http%3A%2F%2Fforesight-server.eurodyn.com%3A8080%2Fshare%2Fpage&state=69958e37-03b8-47fd-904d-f22487538447&login=true&scope=openid

but the redirect_uri should have been somethin like https%3A%2F%2Fforesight.eurodyn.com%2Fshare%2Fpage, since this is the publicly accessed name and not the http%3A%2F%2Fforesight-server.eurodyn.com%3A8080 as this is the internal one.

keep in mind that I have an nginx reverse proxy that takes care of that via:
location /share/ {
       proxy_pass http://foresight-server.eurodyn.com:8080;
       client_max_body_size "5g";
    }
    
    location /alfresco/ {
       proxy_pass http://foresight-server.eurodyn.com:8080;
       client_max_body_size "5g";
    }

**Comment by ayian2004** [comment]
thank you @howkymike and @AFaust 
I have successfully logged into Alfresco Share using Keycloak SSO!!!!
