### ISSUE TITLE
Unable to init docker image alfresco-content-repository-community:7.0.0 using keycloak.repo-1.1.0-rc7-SNAPSHOT.amp (and rc6)

### ISSUE THREAD

**Issue by alvesfonseca** [Acosix/alfresco-keycloak#14]
Hi,

I am experimenting with alfresco-keycloak using docker images (alfresco-content-repository-community:7.0.0), but, as soon as I installed the amps (and theirs dependencies), alfresco-repo is not able to start.

I got the following logs

```
03-Jun-2021 03:07:20.969 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.alfresco.web.app.ContextLoaderListener]
        org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'transformer.acosix-utility.Rfc822ToHtml' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/module/acosix-utility/module-context.xml]: Could not resolve parent bean definition 'baseContentTransformer'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'baseContentTransformer' available
                at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedBeanDefinition(AbstractBeanFactory.java:1417)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedBeanDefinition(AbstractBeanFactory.java:1358)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1344)
```

alfresco-share starts (I get the login screen), but I am unable to login because content services (repo) is not available.

I have both alfresco-global.properties and share-config-custom.xml set.

BTW, I faced the same issue using pre-packaged rc6 amps.

Any debugging suggestion?

Thanks in advance!

**Comment by alvesfonseca** [comment]
Thanks a lot!
