### ISSUE TITLE
Help with configuration and debugging

### ISSUE THREAD

**Issue by mrudev** [Acosix/alfresco-keycloak#34]
Hi Axel,

I am trying to run this module with Alfresco 6.2. I am getting this warning message and can't find a way to get more details - as the url looks correct:
2023-01-13 09:18:19,569 WARN  [de.acosix.alfresco.keycloak.repo.authentication.KeycloakAuthenticationFilter] [http-nio-8080-exec-2] 
Cannot process Keycloak-specifics as Keycloak library was unable to resolve relative URLs from http://localhost:8880/auth

It is just a warning, but seems critical to me (to the functioning of this module). Is there a way to enable further debugging to understand what is going wrong? And would you have an idea as to what the possible root causes of this issue could be?

Furthermore, when I try to login in Share with the admin user, I get something like this (cropped the full stack trace to the relevant lines):
2023-01-13 09:18:19,724 ERROR [org.springframework.extensions.webscripts.AbstractRuntime] [http-nio-8080-exec-2] Exception from executeScript: null
java.lang.NullPointerException
        at java.base/java.net.URI$Parser.parse(URI.java:3104)
        at java.base/java.net.URI.<init>(URI.java:600)
        at java.base/java.net.URI.create(URI.java:881)
        at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
        at de.acosix.alfresco.keycloak.deps.keycloak.adapters.rotation.JWKPublicKeyLocator.sendRequest(JWKPublicKeyLocator.java:97)
        at de.acosix.alfresco.keycloak.deps.keycloak.adapters.rotation.JWKPublicKeyLocator.getPublicKey(JWKPublicKeyLocator.java:63)
        at de.acosix.alfresco.keycloak.deps.keycloak.adapters.rotation.AdapterTokenVerifier.getPublicKey(AdapterTokenVerifier.java:121)
        at de.acosix.alfresco.keycloak.deps.keycloak.adapters.rotation.AdapterTokenVerifier.createVerifier(AdapterTokenVerifier.java:111)
        at de.acosix.alfresco.keycloak.deps.keycloak.adapters.rotation.AdapterTokenVerifier.verifyToken(AdapterTokenVerifier.java:47)
        at de.acosix.alfresco.keycloak.deps.keycloak.adapters.BearerTokenRequestAuthenticator.authenticateToken(BearerTokenRequestAuthenticator.java:103)
        at de.acosix.alfresco.keycloak.deps.keycloak.adapters.BearerTokenRequestAuthenticator.authenticate(BearerTokenRequestAuthenticator.java:88)
        at de.acosix.alfresco.keycloak.repo.authentication.KeycloakRemoteUserMapper.getRemoteUser(KeycloakRemoteUserMapper.java:122)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

Thanks in advance for any suggestions,
Miruna

**Comment by mrudev** [comment]
This had to do with running all services in Docker and needing to use the alias for the identity container instead of localhost in the configuration. Problem is solved now.

**Comment by AFaust** [comment]
Good to know you figured it out before I could even react. Thanks for updating and closing the issue accordingly.
