### ISSUE TITLE
Newbie here

### ISSUE THREAD

**Issue by MilleMilaEmme** [Acosix/alfresco-keycloak#5]
Hi,
My name is Matteo and I'm new at java programming, and I've to make possible the keycloak->Alfresco integration.
I found your project and now I'm trying to compile it correctly. Obviously I need the amp to add to Alfresco.
I'm also new in the use of maven. 
I've correctly done "mvn clean install" to obtain the amp file, but when I try to apply it to Alfresco Community 6.2 the response is:

02190001 An error was encountered during deployment of the AMP into the WAR: 02190000 The following modules must first be installed: [acosix-utility:1.2.5-*]
Module 'acosix-keycloak' installed in '/appsrv/alfresco/6.2.0-ga/tomcat/webapps/alfresco.war'
   -    Title:        Acosix Alfresco Keycloak - Share Module
   -    Version:      1.1.0-rc6

02190001 An error was encountered during deployment of the AMP into the WAR: 02190000 The following modules must first be installed: [acosix-utility:1.2.5-*]
Module 'acosix-keycloak' installed in '/appsrv/alfresco/6.2.0-ga/tomcat/webapps/share.war'
   -    Title:        Acosix Alfresco Keycloak - Share Module
   -    Version:      1.1.0-rc6

now I've tried to add the acosix-utility into the keycloak project modifing the pom file how I've found on internet. But I cannot found it into the lib directory into the target amp file like bcprov-jdk15on-1.66.jar.
How can I do it working? I'm using IntellijIdea.
Thank you a lot!
Many greetings
Matteo

**Comment by AFaust** [comment]
You can get the Acosix Alfresco Utility (core) AMP from Maven Central, e.g. https://search.maven.org/artifact/de.acosix.alfresco.utility/de.acosix.alfresco.utility.core.share and https://search.maven.org/artifact/de.acosix.alfresco.utility/de.acosix.alfresco.utility.core.repository
Also, you only install the Repository module into alfresco.war and the Share module into share.war - not the Share module into both applications.

I am not sure what you found on the internet about modifying the POM of the Acosix Alfresco Keycloak project - that should *not* be done to get the Acosix Alfresco Utility module added to the AMP. Both projects provide their own, separate AMPs (you can also find Acosix Alfresco Keycloak on Maven Central and OSSRH, e.g. https://oss.sonatype.org/#nexus-search;quick~de.acosix.alfresco.keycloak ) that are installed separately + in sequence (first Utility then Keycloak, to avoid the warnings / having to force the install)

**Comment by MilleMilaEmme** [comment]
thanks a lot!
I download the files...
Another question: the apply-amps.sh does not have che possibility to select witch amp file you can install in wich war (alfresco o share) how can I install them separately? 
Thank you very much!
Many greetings 
Matteo

**Comment by AFaust** [comment]
Yes - the `apply_amps.sh` is unfortunately bad in that way, and my suggestions to improve it (provided ~2012) have been ignored. You can either use the `alfresco-mmt` tool directly to install the AMPs in the correct sequence, or run `apply_amps.sh` twice, first with only the Acosix Alfresco Utility AMPs in the amps folders, and then with the Acosix Alfresco Keycloak AMPs added later.

**Comment by MilleMilaEmme** [comment]
Installing alfresco-utility I obtain:

02220001 An error was encountered during deployment of the AMP into the WAR: 02220000 ERROR: The amp will overwrite an existing file in the war '/WEB-INF/lib/jcl-over-slf4j-1.7.25.jar'. Execution halted.  By specifying -force , you can force installation of AMP regardless of the current war state.
so I tried to install with -force.
Now *\share\page does not work, it give me 404 and the log is:

2021-03-22 11:52:47,098 ERROR [org.springframework.web.context.ContextLoader] [main] Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'patch.siteLoadPatch.swsdp' defined in file [/appsrv/alfresco/6.2.0-ga/web-server/webapps/share/WEB-INF/classes/alfresco/module/alfresco-share-services/module-context.xml]: Could not resolve parent bean definition 'basePatch'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'basePatch' available
        at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedBeanDefinition(AbstractBeanFactory.java:1292)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedBeanDefinition(AbstractBeanFactory.java:1235)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1221)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:823)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:400)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)


thank you a lot
Matteo

**Comment by AFaust** [comment]
The 404 error is unrelated to the Acosix Alfresco Utility, but indirectly triggered by it. You have installed the Alfresco Share Service AMP into share.war, but it must be installed into alfresco.war, as it provides the necessary (remote) services in the backend for share.war to work properly. The Acosix Alfresco Utility adds the same module handling support to share.war that is present in alfresco.war, and by doing so, it activates the incorrectly installed module, which fails because of being in the wrong place...

**Comment by MilleMilaEmme** [comment]
hi,
I'm here... 
Thank you very much for your help. I've another problem.
I put the keycloak configuration in the /shared/classes/alfresco-global.properties like:

authentication.chain=alfrescoNtlm1:alfrescoNtlm,keycloak1:keycloak

keycloak.authentication.enabled=true
keycloak.authentication.sso.enabled=true
keycloak.authentication.sso.handlePublicApi=false
keycloak.authentication.allowTicketLogons=true
keycloak.authentication.allowHttpBasicLogon=true
keycloak.authentication.allowUserNamePasswordLogin=true
keycloak.authentication.mapAuthorities=true
keycloak.authentication.mapPersonPropertiesOnLogin=true

keycloak.synchronization.enabled=false
#keycloak.synchronization.userFilter.containedInGroup.property.groupPaths=
#keycloak.synchronization.userFilter.containedInGroup.property.groupIds=
#keycloak.synchronization.groupFilter.containedInGroup.property.groupPaths=
#keycloak.synchronization.groupFilter.containedInGroup.property.groupIds=

keycloak.adapter.auth-server-url=https://keycloak.server:8443/auth
keycloak.adapter.realm=alfresco
keycloak.adapter.resource=alfresco-client
keycloak.adapter.ssl-required=none
keycloak.adapter.confidential-port=-1
keycloak.adapter.public-client=false
keycloak.adapter.credentials.provider=secret
keycloak.adapter.credentials.secret=secret_of_keycloak
# for some reason, this is not a sane default in Keycloak Adapter config
keycloak.adapter.verify-token-audience=true

but when I start the alfresco service in the share.log I see:

2021-03-23 10:03:22,339 WARN  [de.acosix.alfresco.keycloak.share.web.KeycloakAuthenticationFilter] [http-nio-8181-exec-1] Cannot process Keycloak-specifics as Keycloak library was unable to resolve relative URLs from http://localhost:8180/auth
2021-03-23 10:03:22,532 INFO  [org.alfresco.web.site.EditionInterceptor] [http-nio-8181-exec-1] Unable to retrieve License information from Alfresco: 404
2021-03-23 10:03:46,225 WARN  [de.acosix.alfresco.keycloak.share.web.KeycloakAuthenticationFilter] [http-nio-8181-exec-4] Cannot process Keycloak-specifics as Keycloak library was unable to resolve relative URLs from http://localhost:8180/auth
2021-03-23 10:03:46,353 WARN  [de.acosix.alfresco.keycloak.share.web.KeycloakAuthenticationFilter] [http-nio-8181-exec-5] Cannot process Keycloak-specifics as Keycloak library was unable to resolve relative URLs from http://localhost:8180/auth
2021-03-23 10:18:40,186 WARN  [de.acosix.alfresco.keycloak.share.web.KeycloakAuthenticationFilter] [http-nio-8181-exec-3] Cannot process Keycloak-specifics as Keycloak library was unable to resolve relative URLs from http://localhost:8180/auth
2021-03-23 10:18:44,867 WARN  [de.acosix.alfresco.keycloak.share.web.KeycloakAuthenticationFilter] [http-nio-8181-exec-6] Cannot process Keycloak-specifics as Keycloak library was unable to resolve relative URLs from http://localhost:8180/auth
2021-03-23 10:18:44,961 ERROR [org.alfresco.web.site] [http-nio-8181-exec-6] javax.servlet.ServletException: Could not resolve view with name 'keycloak' in servlet with name 'Spring Surf Dispatcher Servlet'

where I have to configure the parameters?
I cannot find the directory alfresco/extension/subsystems/Authentication/keycloak/, I have to create it in 
/web-server/shared/classes/alfresco/extension/ path?
Thank you a lot!
Matteo

**Comment by MilleMilaEmme** [comment]
Hi, 
I'm always here... -_-˚
I think that I've the right configuration on keycloak (like the guide), on the alfresco-global.properties and on the share-config-custom.xml (like the guide).
But now I've this error in the share.log:

javax.servlet.ServletException: Could not resolve view with name 'keycloak' in servlet with name 'Spring Surf Dispatcher Servlet'

"help me Obi Wan Kenobi you're my only hope"
Thank you a lot!

**Comment by MilleMilaEmme** [comment]
Hi, 
I'm stuck into the installation of amp files on alfresco.war.
This is the sequence:

alfresco@/6.2.0-ga$ java -jar ./bin/alfresco-mmt.jar install ./amps/de.acosix.alfresco.keycloak.repo-1.1.0-rc6.amp ./tomcat/webapps/alfresco.war
02260001 An error was encountered during deployment of the AMP into the WAR: 02260000 The following modules must first be installed: [acosix-utility:1.2.5-*]
alfresco@/6.2.0-ga$ java -jar ./bin/alfresco-mmt.jar install ./amps/de.acosix.alfresco.utility.core.repo-1.2.5.amp ./tomcat/webapps/alfresco.war
alfresco@/6.2.0-ga$ java -jar ./bin/alfresco-mmt.jar install ./amps/de.acosix.alfresco.keycloak.repo-1.1.0-rc6.amp ./tomcat/webapps/alfresco.war
02260001 An error was encountered during deployment of the AMP into the WAR: 02260000 The following modules must first be installed: [acosix-utility:1.2.5-*]

The utility amp is already installed, why does it return that error?
Thank you a lot for all
Matteo

**Comment by AFaust** [comment]
Ah... I just realised/remembered. In order to properly handle relations between Alfresco authentication tickets + Keycloak tokens, a dependency on a more aggressive patch in the full Acosix Alfresco Utility module was required. Therefore the Core module alone will not suffice and you need to install the regular AMP of that module instead of the core one (the regular includes the core).
You can technically disable all of the patches of the regular module except for the ones refering to `multipleAuthenticationListeners`

**Comment by MilleMilaEmme** [comment]
thank you a lot!
Now I installed the amps succesfully.
But now I've a new error:
2021-03-31 11:28:30,629 WARN  [org.springframework.beans.GenericTypeAwarePropertyDescriptor] [main] Invalid JavaBean property 'authenticationComponent' being accessed! Ambiguous write methods found next to actually used [public void de.acosix.alfresco.keycloak.repo.authentication.KeycloakAuthenticationServiceImpl.setAuthenticationComponent(de.acosix.alfresco.keycloak.repo.authentication.KeycloakAuthenticationComponent)]: [public void org.alfresco.repo.security.authentication.AuthenticationServiceImpl.setAuthenticationComponent(org.alfresco.repo.security.authentication.AuthenticationComponent)]
2021-03-31 11:28:30,653 WARN  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory$ChildApplicationContext] [main] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'globalAuthenticationFilter' defined in file [/appsrv/alfresco/6.2.0-ga/web-server/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/Authentication/keycloak/keycloak-authentication-context.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.acosix.alfresco.keycloak.repo.authentication.KeycloakAuthenticationFilter]: No default constructor found; nested exception is java.lang.NoClassDefFoundError: org/keycloak/adapters/servlet/OIDCServletHttpFacade
2021-03-31 11:28:30,656 WARN  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] [main] Startup of 'Authentication' subsystem, ID: [Authentication, managed, keycloak1] failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'globalAuthenticationFilter' defined in file [/appsrv/alfresco/6.2.0-ga/web-server/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/Authentication/keycloak/keycloak-authentication-context.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.acosix.alfresco.keycloak.repo.authentication.KeycloakAuthenticationFilter]: No default constructor found; nested exception is java.lang.NoClassDefFoundError: org/keycloak/adapters/servlet/OIDCServletHttpFacade
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1303)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.alfresco.repo.management.subsystems.ChildApplicationContextFactory$ApplicationContextState.start(ChildApplicationContextFactory.java:824)
	at org.alfresco.repo.management.subsystems.AbstractPropertyBackedBean.start(AbstractPropertyBackedBean.java:1098)
	at org.alfresco.repo.management.subsystems.AbstractPropertyBackedBean.getState(AbstractPropertyBackedBean.java:320)
	at org.alfresco.repo.management.subsystems.ChildApplicationContextFactory.getApplicationContext(ChildApplicationContextFactory.java:450)
	at de.acosix.alfresco.utility.repo.subsystems.SubsystemChildApplicationContextManager$SubsystemApplicationContextManagerState.getApplicationContext(SubsystemChildApplicationContextManager.java:338)
	at org.alfresco.repo.management.subsystems.DefaultChildApplicationContextManager$ApplicationContextManagerState.start(DefaultChildApplicationContextManager.java:328)
	at org.alfresco.repo.management.subsystems.AbstractPropertyBackedBean.start(AbstractPropertyBackedBean.java:1098)
	at org.alfresco.repo.management.subsystems.AbstractPropertyBackedBean.getState(AbstractPropertyBackedBean.java:320)
	at org.alfresco.repo.management.subsystems.DefaultChildApplicationContextManager.getInstanceIds(DefaultChildApplicationContextManager.java:187)
	at org.alfresco.repo.admin.patch.impl.AdminUserPatch.afterPropertiesSet(AdminUserPatch.java:111)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:400)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
	at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:70)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4678)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5139)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1848)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:738)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
	
I'm mistaking the configuration?
Thanks

**Comment by AFaust** [comment]
Hmm... did you build the AMP locally instead of downloading it from Maven Central? There should be no reference to a class `org/keycloak/adapters/servlet/OIDCServletHttpFacade` - all dependencies to Keycloak classes in `org/keycloak` should have been rewritten to `de/acosix/alfresco/keycloak`

**Comment by MilleMilaEmme** [comment]
I used amp from Maven Central.
I've alfresco.war and share.war installed time ago, I don't know if they're clean or not, but I've to use that, I cannot lose the work made before...
Do you advise me to restart from new alfresco.war and share.war?
Thank you a lot!

**Comment by AFaust** [comment]
These dependencies are the "old" versions of Keycloak from Alfresco - do not change them. Any Keycloak dependencies that my module needs is part of the JAR. Since you initially tried to install the addon via JAR method, I would advise you to start from a clean alfresco.war and only install the AMPs this time - it could be that you still have one of the manually installed JARs in the application which messes things up.

**Comment by MilleMilaEmme** [comment]
hi, I see that Alfresco Community 7 is downloadable. In an old post you wrote that this version resolve the problem of the integration with keycloak like your plugin. If I install 7 instead of 6.2 I can resolve?
Thanks!

**Comment by MilleMilaEmme** [comment]
Hello, I'm here... Now we restart all with a new installation of alfresco 6.2. Now we've this error:

org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'patch.siteLoadPatch.swsdp' defined in file [/appsrv/alfresco/6.2.0-ga/web-server/webapps/share/WEB-INF/classes/alfresco/module/alfresco-share-services/module-context.xml]: Could not resolve parent bean definition 'basePatch'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'basePatch' available
    at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedBeanDefinition(AbstractBeanFactory.java:1292)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedBeanDefinition(AbstractBeanFactory.java:1235)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1221)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:823)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:400)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4678)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5139)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
    at org.apache.catalina.core.StandardContext.reload(StandardContext.java:3754)
    at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1403)
    at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1313)
    at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1611)
    at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:305)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
    at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1151)
    at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1353)
    at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1357)
    at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1335)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'basePatch' available
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:771)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1221)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedBeanDefinition(AbstractBeanFactory.java:1008)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedBeanDefinition(AbstractBeanFactory.java:1276)
    ... 28 more
12-Apr-2021 17:13:41.991 SEVERE [Catalina-utility-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
12-Apr-2021 17:13:41.991 SEVERE [Catalina-utility-1] org.apache.catalina.core.StandardContext.startInternal Context [/share] startup failed due to previous errors
12-Apr-2021 17:13:42.013 INFO [Catalina-utility-1] org.apache.catalina.core.StandardContext.reload Reloading Context with name [/share] is completed

on 
https://hub.alfresco.com/t5/alfresco-content-services-hub/how-to-disable-the-sample-site/ba-p/293266 I've found that I've to set:
sample.site.disabled=true
but it doesn't work...

How can we make it work?
Thank you!

**Comment by AFaust** [comment]
You have installed the Alfresco Search Services AMP into the wrong web application. YOu have installed it into Share where it does not belong. It is an AMP for ACS Repository to enable it to support functionalities that Share needs. By installing Acosix Alfresco Utility, you have enabled a patch that adds the same kind of module loading behaviour to Share as exists in ACS Repository - this triggers the incorrectly installed Alfresco Share Service AMP, which then fails. Remove the Alfresco Search Service AMP from the Share web application and this issue should be fixed.
